-- =====================================================================
-- 1. Tabele na zrzuty (snapshoty) raportu "Koszty noclegów pracowniczych"
--    Uruchom raz w schemacie parsującym aplikacji (SQL Workshop > SQL Commands
--    albo SQL Scripts).
-- =====================================================================

-- Nagłówek zrzutu: jeden wiersz = jeden zamrożony miesiąc.
-- Osobna tabela, bo zrzut może mieć 0 wierszy danych, a i tak ma "istnieć".
create table fs_noclegi_snap_hdr (
    snap_id        number generated by default on null as identity primary key,
    rok            number(4)      not null,
    miesiac        number(2)      not null,
    ilosc_wierszy  number,
    utworzyl       varchar2(255)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    utworzono      date           default on null sysdate not null,
    constraint fs_noclegi_snap_hdr_uk unique (rok, miesiac)
);

-- Dane zrzutu: kolumny 1:1 z wynikiem zapytania online.
create table fs_noclegi_snap (
    snap_id              number        not null
                         constraint fs_noclegi_snap_fk references fs_noclegi_snap_hdr (snap_id) on delete cascade,
    rok                  number(4)     not null,
    miesiac              number(2)     not null,
    miesiac_rok          varchar2(10),
    geid                 varchar2(100),
    imie                 varchar2(400),
    nazwisko             varchar2(400),
    num_dok              varchar2(200),
    mpk                  varchar2(100),
    projekt              varchar2(400),
    spolka               varchar2(100),
    typ_umowy            varchar2(200),
    lokal                varchar2(1000),
    ilosc_nocl           number,
    ilosc_nocl_umowa     number,
    obciazenie_proj      number,
    kwota_dzien          number,
    info                 varchar2(100),
    kwota_zakwat         number,
    kwota_zakwat_umowa   number,
    korekta              varchar2(50),
    suma                 number
);

create index fs_noclegi_snap_i1 on fs_noclegi_snap (rok, miesiac, spolka);
create index fs_noclegi_snap_i2 on fs_noclegi_snap (snap_id);
